### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ferhung-mtk**

### CODE REVIEW

**Comment by ferhung-mtk** [comment]
Which device are u using? I will update it after a few days. Next one will be better.

**Comment by ponnex** [comment]
Its cherry mobile flare 3 another mt6582 device :) still working on making
a right defconfig. Will be expecting for that soon

cheers!

**Comment by ferhung-mtk** [comment]
Good, are you using this kernel source too?

**Comment by ponnex** [comment]
tried compiling once before but run an error, dont have much time lately so
havent tried again yet. Maybe I can work on it later since its the start of
holiday break :)

**Comment by ferhung-mtk** [comment]
U should find your own kernel drivers. Next one will be better.

**Comment by ferhung-mtk** [comment]
Updating now. CHECK!
More things are working well in this new source.
https://github.com/ferhung-mtk/MT6582-LP-KERNEL

**Pull request merged**
